version: '3'

services:
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 8080:8080
    command: ["npm", "run", "serve"]

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: viacep-challenge
      MYSQL_USER: viacep
      MYSQL_PASSWORD: viacep
    ports:
      - "3340:3340"
